client_config_backend: file
client_config:
    client_id: 591253696860-f1gh58ru28iqba7s1mfamhp2123dsura.apps.googleusercontent.com
    client_secret: mtxY8foTCMbY_rFPhwObVaSm

save_credentials: True
save_credentials_backend: file
save_credentials_file: credentials.json

get_refresh_token: True

oauth_scope:
    - https://www.googleapis.com/auth/drive